# Instructions to run:
# cd to folder containing this file
# conda env create
# source activate ainext

name: ainext
channels:
- defaults
dependencies:
- python=3.6
- pip==9.0.3
- numpy==1.14.2
- jupyter==1.0.0
- matplotlib==2.2.2
- scikit-learn==0.19.1
- scipy==1.0.1
- pandas==0.22.0
- pillow==5.0.0
- seaborn==0.8.1
- h5py==2.7.1
- pytest==3.5.0
- pip:
  - tensorflow==1.7.0
  - keras==2.1.5
